In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df = pd.read_excel("tugbahoca.xlsx")

df = np.array(df)
df

array([[ 2,  4],
       [-2,  0],
       [ 3,  5],
       [ 1,  1],
       [-1,  2]], dtype=int64)

In [3]:
x1 = np.split(df, 2, axis=1)[0]
y = np.split(df, 2, axis=1)[1]

In [4]:
# y yanıt vektörümüz
y 

array([[4],
       [0],
       [5],
       [1],
       [2]], dtype=int64)

In [5]:
# x regresör matrisimizi oluşturacağız
x1 

array([[ 2],
       [-2],
       [ 3],
       [ 1],
       [-1]], dtype=int64)

In [6]:
# regresör matrisimize ekleyeceğimiz B0 matrisimiz
a = np.ones((5,1), dtype=int) # dtype'ı int olan 1x5 boyutunda 1'lerden oluşan bir matris oluştur


In [7]:
x = np.append(a, x1, axis=1) # x1'e a'yı sütun olarak ekle "AYNI BOYUTTA OLMALILAR"
x

array([[ 1,  2],
       [ 1, -2],
       [ 1,  3],
       [ 1,  1],
       [ 1, -1]], dtype=int64)

In [8]:
# Beta şapka = [x'x]tersi . x'y dir 
transpose_x = np.transpose(x)
transpose_x

array([[ 1,  1,  1,  1,  1],
       [ 2, -2,  3,  1, -1]], dtype=int64)

In [77]:
tersi_alınacak_degisken = transpose_x.dot(x) # x'x i bulduk
tersi_alınacak_degisken

array([[ 5,  3],
       [ 3, 19]], dtype=int64)

In [78]:
# tersini alalım
inverse_x = np.linalg.inv(tersi_alınacak_degisken)
inverse_x

array([[ 0.22093023, -0.03488372],
       [-0.03488372,  0.05813953]])

In [79]:
# x'y yi bulalım
c = transpose_x.dot(y)
c

array([[12],
       [22]], dtype=int64)

In [82]:
# Beta şapka bulalım
beta_sapka = inverse_x.dot(c)
beta_sapka

array([[1.88372093],
       [0.86046512]])

In [81]:
# Yukarıda y şapkayı bulmuş olduk yşapka = 1.88 + 0.86x