In [15]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [16]:
data = pd.read_excel("tugbahocaders.xlsx")
data

Gelir(X)  Eğitim(Y)
0        13          3
1        18          4
2        24          6
3        31          9
4        25          8
5        45         15
6        54         11

In [17]:
data = np.array(data) # datayı matris haline getirelim
data

array([[13,  3],
       [18,  4],
       [24,  6],
       [31,  9],
       [25,  8],
       [45, 15],
       [54, 11]], dtype=int64)

In [18]:
x = np.split(data, 2, axis=1)[0] # datayı x ve ye olarak iki matrise ayıralım
y = np.split(data, 2, axis=1)[1]


In [19]:
x # katsayılar matrisi

array([[13],
       [18],
       [24],
       [31],
       [25],
       [45],
       [54]], dtype=int64)

In [20]:
y # yanıt vektörü

array([[ 3],
       [ 4],
       [ 6],
       [ 9],
       [ 8],
       [15],
       [11]], dtype=int64)

In [14]:
a = np.ones((7,1), dtype=int) # x matrisine 1'lerden oluşan b0 ı temsil eden vektörümüzü ekleyelim

x1 = np.append(a, x, axis=1)
x1

array([[ 1, 13],
       [ 1, 18],
       [ 1, 24],
       [ 1, 31],
       [ 1, 25],
       [ 1, 45],
       [ 1, 54]], dtype=int64)

In [9]:
transpose_x1 = np.transpose(x1) # transpozunu alalım

In [10]:
c = transpose_x1.dot(x1) # transpozu ile kendisini çarpalım
c

array([[   7,  210],
       [ 210, 7596]], dtype=int64)

In [11]:
inverse_x = np.linalg.inv(c) # transpozunu alıp çarptığımız değerin tersini alalım
inverse_x

array([[ 8.37301587e-01, -2.31481481e-02],
       [-2.31481481e-02,  7.71604938e-04]])

In [12]:
g = transpose_x1.dot(y) # x'y kısmı
g

array([[  56],
       [2003]], dtype=int64)

In [13]:
final_model = inverse_x.dot(g) # formülü komple yerine yazıyoruz = [x'x]tersi . x'y
final_model

array([[0.52314815],
       [0.2492284 ]])

In [22]:
# y = 0.5231 + 0.2492x fit edilen modelimiz