In [21]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [22]:
data = pd.read_excel("tugbahocaders2.xlsx") #datayı aldık

data = np.array(data)
data

array([[ 6,  1,  1],
       [ 6,  2,  1],
       [11,  2,  2],
       [ 9,  1,  3],
       [16,  3,  3],
       [16,  1,  5],
       [ 4,  1,  1],
       [ 8,  3,  1],
       [11,  2,  2],
       [13,  1,  2]], dtype=int64)

In [23]:
y = np.split(data, 3, axis=1)[0] # bağımlı ve bağımsız değiskenler olusturuldu
x1 = np.split(data, 3, axis=1)[1]
x2 = np.split(data, 3, axis=1)[2]

In [24]:
y

array([[ 6],
       [ 6],
       [11],
       [ 9],
       [16],
       [16],
       [ 4],
       [ 8],
       [11],
       [13]], dtype=int64)

In [25]:
ones = np.ones((10,1), dtype=int) # Beta 0 icin katsayılarımız

In [26]:
reg1 = np.append(x1, x2, axis=1) #katsayılar matrisi icin bağımsız degiskenleri birlestirdik
reg1

array([[1, 1],
       [2, 1],
       [2, 2],
       [1, 3],
       [3, 3],
       [1, 5],
       [1, 1],
       [3, 1],
       [2, 2],
       [1, 2]], dtype=int64)

In [27]:
reg = np.append(ones, reg1, axis=1) # beta sıfır icin katsayıları olan 1'leri de ekledik
reg

array([[1, 1, 1],
       [1, 2, 1],
       [1, 2, 2],
       [1, 1, 3],
       [1, 3, 3],
       [1, 1, 5],
       [1, 1, 1],
       [1, 3, 1],
       [1, 2, 2],
       [1, 1, 2]], dtype=int64)

In [28]:
transpose_reg = np.transpose(reg) # transpoz alma islemi
transpose_reg

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 2, 2, 1, 3, 1, 1, 3, 2, 1],
       [1, 1, 2, 3, 3, 5, 1, 1, 2, 2]], dtype=int64)

In [33]:
tersi_alınacak_degisken = transpose_reg.dot(reg) #tersi almadan önce carpım
tersi_alınacak_degisken

array([[10, 17, 21],
       [17, 35, 34],
       [21, 34, 59]], dtype=int64)

In [30]:
inverse_reg = np.linalg.inv(tersi_alınacak_degisken) #ters alma
inverse_reg

array([[ 1.03295455, -0.32840909, -0.17840909],
       [-0.32840909,  0.16931818,  0.01931818],
       [-0.17840909,  0.01931818,  0.06931818]])

In [31]:
# x'y yi bulalım
c = transpose_reg.dot(y)
c

array([[100],
       [176],
       [249]], dtype=int64)

In [32]:
beta_sapka = inverse_reg.dot(c) # b0, b1 ve b2 icin katsayılarımız
beta_sapka

array([[1.07159091],
       [1.76931818],
       [2.81931818]])

In [20]:
transpose_reg

array([[1, 1, 1],
       [1, 2, 1],
       [1, 2, 2],
       [1, 1, 3],
       [1, 3, 3],
       [1, 1, 9],
       [1, 1, 1],
       [1, 3, 1],
       [1, 2, 2],
       [1, 1, 2]], dtype=int64)

In [46]:
h = np.linalg.det(tersi_alınacak_degisken)

In [48]:
adjoint_matrix = inverse_reg.dot(h)
adjoint_matrix

array([[ 909., -289., -157.],
       [-289.,  149.,   17.],
       [-157.,   17.,   61.]])